[workspace]
members = [".", "crypt"]

[package]
name = "pezzo"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "pezzo"
path = "src/pezzo/main.rs"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[features]

[build-dependencies]
bindgen = "0.64.0"

[target.'cfg(unix)'.dependencies]
memchr = "2.5.0"
libc = "0.2.140"

[target.'cfg(target_os = "linux")'.dependencies]
atoi = "2.0.0"
ctor = "0.2.0"

[dependencies]
peg = "0.8.1"
clap = { version = "4.1.13", features = ["derive"] }
which = "4.4.0"
globset = { version = "0.4.10", features = ["simd-accel"] }
anyhow = "1.0.70"
