[workspace]
members = [".", "crypt", "pam", "secure-read"]

[package]
name = "pezzo"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "pezzo"
path = "src/pezzo/main.rs"

[profile.release]
strip = true
opt-level = 3
# lto = true
codegen-units = 1

[features]

[build-dependencies]
memchr = "2.5.0"

[target.'cfg(unix)'.dependencies]
memchr = "2.5.0"
libc = "0.2.140"
tty-info = { git = "https://www.github.com/shurizzle/tty-info.git" }
unix-clock = { git = "https://www.github.com/shurizzle/unix-clock.git" }
cfg-if = "1.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
linux-syscalls = "0.2.0"
linux-stat = "0.3.1"
linux-raw-sys = "0.4.3"

[dependencies]
peg = "0.8.1"
clap = { version = "4.1.13", features = ["derive"] }
globset = { version = "0.4.10", features = ["simd-accel"] }
anyhow = "1.0.70"
secure-read = { path = "secure-read", features = ["pam-compat"] }
pam = { path = "pam" }
