[package]
name = "pam"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.66.1"
which = "4.4.0"
phf = { version = "0.11.2", features = ["macros"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.147"
